### ISSUE TITLE
branding: rename noVNC

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renkulab-docker#151]
The default vnc.html file has `noVNC` as the title and so tabs in browsers will show this. I think we should rebrand this to something like RENKU VNC/RENKU Desktop/Renku VNC/Renku Desktop.

Thoughts?

https://github.com/SwissDataScienceCenter/renkulab-docker/blob/20f653dc79d2970141f188e2f85f99baecde46b4/docker/vnc/vnc_renku.html#L17

(We have already 'doctored' this .html (to add full screen functionality))

**Comment by erbou** [comment]
_Thoughts?_: I agree

Comments:

- I would prefer a name with _Desktop_ in it, and avoid using VNC (everywhere) - not everyone knows VNC.

- Should the favicon be changed? e.g. jupyterlab has its own, and it is useful when we need to find interactive environment tabs among many open tabs.

- Possibly another issue for vnc.html: when in full screen, the top bar serves little purpose other than providing a clue about the interactive environment. The (un)`Full Screen` button is not needed since that can be done with `ESC` (the browser will happily remind you of that), and `Ctrl-Alt-Del` is only for certain OS. Should we therefore hide the bar, and regain a bit of screen space?

**Comment by gavin-k-lee** [comment]
Agree with the above. 
- The current favicon is the default SDSC one - maybe it could be a renku frog favicon?
- For the full screen - do you mean hide the bar when in full-screen mode? I think it'd still be good to show the option somewhere when still in non-full-screen mode

**Comment by gavin-k-lee** [comment]
The 'full' `vnc.html` provides more features that can be made use of, e.g. clipboard and full screen. (See #152) We can test that out and customise the favicon etc.

**Comment by erbou** [comment]
Agree, the clipboard feature is needed. Note that the 'full' vnc.html stays in the way when in full screen. My preference would be to have no, or a very minimalist vnc interface in that mode. Ideally I would like to hide the bar when in full-screen mode and show it in non-full screen (that was my earlier comment).
